[tool.ruff]
line-length = 120
indent-width = 4
builtins = ["_"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint]
select = ["E", "F"]
# ignore = ["F821", "E402"]


[tool.pyright]
typeCheckingMode = "off"
exclude = ["**/builddir"]
reportMissingImports = true
reportUndefinedVariable = false
reportMissingModuleSource = false
stubPath = "/home/tim/.local/lib/python3.13/site-packages/"
# typeshedPath = "/home/tim/.local/lib/python3.13/site-packages/"
