# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright (C) 2024 Tim Lauridsen

from typing import Iterable, Protocol

from yumex.backend import TransactionResult
from yumex.backend.dnf import TransactionOptions, YumexPackage
from yumex.utils.enums import InfoType, PackageFilter, Page
from yumex.utils.types import MainWindow


class PackageCache(Protocol):
    """Protocol class for a package cache"""

    def get_packages_by_filter(self, pkgfilter: PackageFilter, reset=False) -> list[YumexPackage]: ...

    def get_packages(self, pkgs: list[YumexPackage]) -> list[YumexPackage]: ...

    def get_package(self, pkg: YumexPackage) -> YumexPackage: ...


class PackageBackend(Protocol):
    """Protocol class for a package backend"""

    def get_packages(self, pkg_filter: PackageFilter) -> list[YumexPackage]: ...

    def search(self, txt: str, options: dict) -> list[YumexPackage]: ...

    def get_package_info(self, pkg: YumexPackage, attr: InfoType) -> str | None: ...

    def get_repositories(self) -> list[str]: ...

    def depsolve(self, pkgs: Iterable[YumexPackage]) -> list[YumexPackage]: ...

    def build_transaction(self, pkgs: list[YumexPackage], opts: TransactionOptions) -> TransactionResult: ...

    def run_transaction(self, opts: TransactionOptions) -> TransactionResult: ...

    def has_offline_transaction(self) -> bool: ...

    def cancel_offline_transaction(self) -> bool: ...

    def reboot_and_install(self) -> bool: ...


class Progress(Protocol):
    def show(self) -> None: ...

    def hide(self) -> None: ...

    def set_title(self, title: str) -> None: ...

    def set_subtitle(self, title: str) -> None: ...

    def set_progress(self, frac: float) -> None: ...


class Presenter(Protocol):
    """Protocol class for a presenter in  a Model-view-presenter (MVP) architectural pattern"""

    @property
    def progress(self) -> Progress: ...

    def reset_backend(self, reopen: bool) -> None: ...

    def reset_cache(self) -> None: ...

    def get_main_window(self) -> MainWindow: ...

    def show_message(self, title, timeout=2) -> None: ...

    def set_needs_attention(self, page: Page, num: int) -> None: ...

    def confirm_flatpak_transaction(self, refs: list) -> bool: ...

    def select_page(self, page: Page) -> None: ...

    def set_window_sesitivity(self, sensitive: bool): ...

    @property
    def package_backend(self) -> PackageBackend: ...

    @property
    def package_cache(self) -> PackageCache: ...

    @property
    def flatpak_backend(self): ...

    def reset_flatpak_backend(self) -> None: ...

    def search(self, txt: str, limit: int, options: dict) -> list[YumexPackage]: ...

    def get_package_info(self, pkg: YumexPackage, attr: InfoType) -> str | None: ...

    def get_repositories(self) -> list[(str, str, bool, int)]: ...

    def depsolve(self, pkgs: Iterable[YumexPackage]) -> list[YumexPackage]: ...

    def get_packages_by_filter(self, pkgfilter: PackageFilter, reset=False) -> list[YumexPackage]: ...

    def get_packages(self, pkgs: list[YumexPackage]) -> list[YumexPackage]: ...

    def get_package(self, pkg: YumexPackage) -> YumexPackage: ...

    def confirm_gpg_import(self, key_values): ...

    def has_offline_transaction(self) -> bool: ...

    def cancel_offline_transaction(self) -> bool: ...

    def reboot_and_install(self) -> bool: ...
